IF SCHEMA_ID(N'ampliacion') IS NULL EXEC(N'CREATE SCHEMA [ampliacion] AUTHORIZATION dbo;');
GO
IF SCHEMA_ID(N'cmn') IS NULL EXEC(N'CREATE SCHEMA [cmn] AUTHORIZATION dbo;');
GO
IF SCHEMA_ID(N'ejecucion') IS NULL EXEC(N'CREATE SCHEMA [ejecucion] AUTHORIZATION dbo;');
GO
IF SCHEMA_ID(N'integracion') IS NULL EXEC(N'CREATE SCHEMA [integracion] AUTHORIZATION dbo;');
GO
IF SCHEMA_ID(N'pago') IS NULL EXEC(N'CREATE SCHEMA [pago] AUTHORIZATION dbo;');
GO
IF SCHEMA_ID(N'requerimiento') IS NULL EXEC(N'CREATE SCHEMA [requerimiento] AUTHORIZATION dbo;');
GO
IF SCHEMA_ID(N'resolucion') IS NULL EXEC(N'CREATE SCHEMA [resolucion] AUTHORIZATION dbo;');
GO
IF SCHEMA_ID(N'siga') IS NULL EXEC(N'CREATE SCHEMA [siga] AUTHORIZATION dbo;');
GO
IF SCHEMA_ID(N'sigcm') IS NULL EXEC(N'CREATE SCHEMA [sigcm] AUTHORIZATION dbo;');
GO
