/*
  Base    : DBSIGCM
  Esquema : siga
  Objeto  : siga.SIG_TECHO_PRESUPUESTO
  Tipo    : SYNONYM
  Extraido: 2026-08-18 11:59:35
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SYNONYM [siga].[SIG_TECHO_PRESUPUESTO] FOR [SIGA_1750].[dbo].[SIG_TECHO_PRESUPUESTO];
GO
