/*
  Base    : DBSIGCM
  Esquema : siga
  Objeto  : siga.SIG_CUADRO_X_CENTRO
  Tipo    : SYNONYM
  Extraido: 2026-08-18 11:59:35
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SYNONYM [siga].[SIG_CUADRO_X_CENTRO] FOR [SIGA_1750].[dbo].[SIG_CUADRO_X_CENTRO];
GO
