/*
  Base    : DBSIGCM
  Esquema : siga
  Objeto  : siga.CATALOGO_BIEN_SERV
  Tipo    : SYNONYM
  Extraido: 2026-08-18 11:59:35
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SYNONYM [siga].[CATALOGO_BIEN_SERV] FOR [SIGA_1750].[dbo].[CATALOGO_BIEN_SERV];
GO
