/*
  Base    : DBSIGCM
  Esquema : siga
  Objeto  : siga.SIG_CENTRO_COSTO_TAREA
  Tipo    : SYNONYM
  Extraido: 2026-08-18 11:59:35
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SYNONYM [siga].[SIG_CENTRO_COSTO_TAREA] FOR [SIGA_1750].[dbo].[SIG_CENTRO_COSTO_TAREA];
GO
