/*
  Base    : DBSIGCM
  Esquema : siga
  Objeto  : siga.SIG_PARAMETRO_EJECUTORA_ANIO
  Tipo    : SYNONYM
  Extraido: 2026-08-18 11:59:35
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SYNONYM [siga].[SIG_PARAMETRO_EJECUTORA_ANIO] FOR [SIGA_1750].[dbo].[SIG_PARAMETRO_EJECUTORA_ANIO];
GO
